id: P000366
initial_creation_type: ocr
source_metadata:
  id: bdr:W23753
  title: རྡོ་རྗེ་ཕུར་པ་སྤུ་གྲི་རེག་གཅོད་སྐོར
  author: ''
  volumes:
    e891e94562904272b90029831d8e8a8a:
      image_group_id: I2608
      title: ''
      volume_number: 1
      total_pages: 224
      base_file: v001.txt
ebook_metadata:
  title: རྡོ་རྗེ་ཕུར་པ་སྤུ་གྲི་རེག་གཅོད་སྐོར
  author: ''
  sku: P000366
  cover: cover.jpg
  layers:
  - pagination
