id: P000366
initial_creation_type: ocr
created_at: 16/03/2020
last_modified_at: 2021-12-16 15:36:16.827694
source_metadata:
  id: bdr:W23753
  title: རྡོ་རྗེ་ཕུར་པ་སྤུ་གྲི་རེག་གཅོད་སྐོར
  author: ''
  volumes:
    e891e94562904272b90029831d8e8a8a:
      image_group_id: I2608
      title: ''
      volume_number: 1
      total_pages: 224
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
